EXPERIMENT:
  NAME: "teacher_ShuffleV2"
  TAG: "resnet56"
  PROJECT: "cifar100_teacher_baselines"
DISTILLER:
  TYPE: "NONE"
  TEACHER: "ShuffleV2"
SOLVER:
  BATCH_SIZE: 64
  EPOCHS: 240
  LR: 0.05
  LR_DECAY_STAGES: [150, 180, 210]
  LR_DECAY_RATE: 0.1
  WEIGHT_DECAY: 0.0005
  MOMENTUM: 0.9
  TYPE: "SGD"
